# Generated by Django 3.1.7 on 2021-03-29 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('events', '0002_events_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='payment',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.payment'),
        ),
    ]
