# Generated by Django 3.1.7 on 2021-03-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20210329_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='payment',
        ),
        migrations.AddField(
            model_name='events',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
