# Generated by Django 3.1.7 on 2021-04-27 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_events_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
