# Generated by Django 3.1.7 on 2021-04-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Success'), (2, 'Cancelled'), (3, 'Failed')], default=0),
        ),
    ]
